# Disable sudo to speed up the build
sudo: false

os: osx

# Set the build language to Python
language: python

# Set the python version to 2.7
python: 3.6

# Install the codecov pip dependency
# install:
#   - pip install codecov

script:
#  - coverage run sayHello.py
  - python3 Tr.py urfu.ru


# Push the results back to codecov
# after_success:
#   - codecov
notifications:
  slack:
    on_success: always
